export const hobbiesOptions = [
  { key: "reading", label: "Reading" },
  { key: "painting", label: "Painting" },
  { key: "playingAnInstrument", label: "Playing an instrument" },
  { key: "swimming", label: "Swimming" },
  { key: "cooking", label: "Cooking" },
  { key: "hiking", label: "Hiking" },
  { key: "photography", label: "Photography" },
  { key: "dancing", label: "Dancing" },
  { key: "chess", label: "Chess" },
  { key: "gardening", label: "Gardening" },
  { key: "iceHockey", label: "Ice Hockey" },
  { key: "skiing", label: "Skiing" },
  { key: "snowboarding", label: "Snowboarding" },
  { key: "curling", label: "Curling" },
  { key: "soccer", label: "Soccer" },
  { key: "basketball", label: "Basketball" },
  { key: "canoeing", label: "Canoeing" },
  { key: "kayaking", label: "Kayaking" },
  { key: "cycling", label: "Cycling" },
  { key: "fishing", label: "Fishing" },
];
