export const profesionalSectorOptions = [
  { key: "information_technology", label: "Information Technology" },
  { key: "healthcare", label: "Healthcare" },
  { key: "engineering", label: "Engineering" },
  { key: "finance", label: "Finance" },
  { key: "education", label: "Education" },
  { key: "natural_resources", label: "Natural Resources" },
  { key: "manufacturing", label: "Manufacturing" },
  { key: "construction", label: "Construction" },
  { key: "agriculture", label: "Agriculture" },
  {
    key: "government_administration",
    label: "Government and Public Administration",
  },
  { key: "arts_culture", label: "Arts and Culture" },
  { key: "hospitality_tourism", label: "Hospitality and Tourism" },
  { key: "transportation_logistics", label: "Transportation and Logistics" },
  { key: "retail", label: "Retail" },
  { key: "legal", label: "Legal" },
  { key: "media_communication", label: "Media and Communication" },
  { key: "consulting", label: "Consulting" },
  { key: "nonprofit_social_services", label: "Nonprofit and Social Services" },
  { key: "real_estate", label: "Real Estate" },
  { key: "research_development", label: "Research and Development" },
  { key: "science_technology", label: "Science and Technology" },
  { key: "environmental", label: "Environmental" },
  { key: "sports_recreation", label: "Sports and Recreation" },
  { key: "entertainment", label: "Entertainment" },
  { key: "aviation", label: "Aviation" },
  { key: "pharmaceuticals", label: "Pharmaceuticals" },
  { key: "telecommunications", label: "Telecommunications" },
  { key: "automotive", label: "Automotive" },
  { key: "marketing_advertising", label: "Marketing and Advertising" },
  { key: "human_resources", label: "Human Resources" },
  { key: "fashion_apparel", label: "Fashion and Apparel" },
];
